import type { AIModel, VideoProject, User, CreditTransaction, ABTest } from '@/types'

export const AI_MODELS: AIModel[] = [
  {
    id: 'veo-3-1',
    name: 'Veo 3.1',
    provider: 'Google',
    description: 'Best overall quality with native audio generation. Supports 4K output and exceptional prompt adherence.',
    features: ['4K Output', 'Native Audio', 'Best Prompt Adherence', 'Long Duration'],
    maxDuration: 25,
    costPerSecond: 0.75,
    supportsAudio: true,
    supportsImageInput: true,
    supportsVideoInput: false,
    quality: 'ultra',
    color: '#4285F4',
    icon: 'Sparkles',
  },
  {
    id: 'kling-3-0',
    name: 'Kling 3.0',
    provider: 'Kuaishou',
    description: 'Best value for money. Excellent motion quality with 5-language lip-sync and multi-character dialogue.',
    features: ['Lip Sync', 'Multi-Character', 'Great Value', '15s Clips'],
    maxDuration: 15,
    costPerSecond: 0.25,
    supportsAudio: true,
    supportsImageInput: true,
    supportsVideoInput: true,
    quality: 'high',
    color: '#FF6B35',
    icon: 'Zap',
  },
  {
    id: 'runway-gen-4-5',
    name: 'Runway Gen-4.5',
    provider: 'Runway',
    description: 'Best creative control with camera movements, editing suite, and professional-grade output.',
    features: ['Camera Control', 'Editing Suite', 'Professional', 'Motion Brush'],
    maxDuration: 20,
    costPerSecond: 0.50,
    supportsAudio: false,
    supportsImageInput: true,
    supportsVideoInput: true,
    quality: 'high',
    color: '#FF3366',
    icon: 'Film',
  },
  {
    id: 'pika-2-5',
    name: 'Pika 2.5',
    provider: 'Pika Labs',
    description: 'Fastest iteration for social creators. Great effects and quick turnaround times.',
    features: ['Fast Generation', 'Social Optimized', 'Effects', 'Easy Use'],
    maxDuration: 5,
    costPerSecond: 0.20,
    supportsAudio: false,
    supportsImageInput: true,
    supportsVideoInput: false,
    quality: 'standard',
    color: '#A855F7',
    icon: 'Wand2',
  },
  {
    id: 'luma-ray-3',
    name: 'Luma Ray 3',
    provider: 'Luma AI',
    description: 'Elegant b-roll generation with clean API. Perfect for commercial and brand content.',
    features: ['Clean API', 'B-Roll Focus', 'Commercial Ready', 'Fast'],
    maxDuration: 10,
    costPerSecond: 0.30,
    supportsAudio: false,
    supportsImageInput: true,
    supportsVideoInput: false,
    quality: 'high',
    color: '#10B981',
    icon: 'Sun',
  },
  {
    id: 'seedance-2-0',
    name: 'Seedance 2.0',
    provider: 'ByteDance',
    description: 'Frontier quality with native multi-shot generation. Best for cinematic sequences.',
    features: ['Multi-Shot', 'Cinematic', 'Frontier Quality', 'Native Audio'],
    maxDuration: 20,
    costPerSecond: 0.60,
    supportsAudio: true,
    supportsImageInput: true,
    supportsVideoInput: true,
    quality: 'ultra',
    color: '#F59E0B',
    icon: 'Crown',
  },
]

export const ASPECT_RATIOS = [
  { value: '16:9' as const, label: 'Landscape 16:9', description: 'YouTube, presentations' },
  { value: '9:16' as const, label: 'Portrait 9:16', description: 'TikTok, Reels, Stories' },
  { value: '1:1' as const, label: 'Square 1:1', description: 'Instagram, ads' },
  { value: '4:3' as const, label: 'Standard 4:3', description: 'Classic format' },
  { value: '21:9' as const, label: 'Cinematic 21:9', description: 'Ultra-wide, films' },
]

export const VIDEO_STYLES = [
  'Cinematic',
  'Anime',
  'Photorealistic',
  '3D Animation',
  'Documentary',
  'Commercial',
  'Music Video',
  'Vlog',
  'Sci-Fi',
  'Fantasy',
]

export const MOCK_USER: User = {
  id: 'user-1',
  email: 'creator@cineforge.ai',
  name: 'Alex Creator',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  plan: 'pro',
  credits: 2450,
  totalVideos: 47,
  createdAt: '2026-01-15T10:00:00Z',
}

export const MOCK_PROJECTS: VideoProject[] = [
  {
    id: 'proj-1',
    title: 'Neon Tokyo Drift',
    prompt: 'A cyberpunk street scene in Tokyo at night, neon lights reflecting on wet pavement, a lone figure walking through the rain',
    model: AI_MODELS[0],
    status: 'completed',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    videoUrl: '#',
    duration: 8,
    createdAt: '2026-07-28T14:30:00Z',
    updatedAt: '2026-07-28T14:35:00Z',
    creditsUsed: 6,
    aspectRatio: '16:9',
    style: 'Cinematic',
  },
  {
    id: 'proj-2',
    title: 'Mountain Sunrise',
    prompt: 'Epic sunrise over snow-capped mountains, golden light breaking through clouds, cinematic drone shot',
    model: AI_MODELS[2],
    status: 'completed',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    videoUrl: '#',
    duration: 5,
    createdAt: '2026-07-27T09:15:00Z',
    updatedAt: '2026-07-27T09:20:00Z',
    creditsUsed: 2.5,
    aspectRatio: '16:9',
    style: 'Documentary',
  },
  {
    id: 'proj-3',
    title: 'Product Showcase',
    prompt: 'Sleek product reveal of a luxury watch, rotating on a marble surface, soft studio lighting',
    model: AI_MODELS[4],
    status: 'generating',
    duration: 6,
    createdAt: '2026-07-30T05:00:00Z',
    updatedAt: '2026-07-30T05:00:00Z',
    creditsUsed: 1.8,
    aspectRatio: '1:1',
    style: 'Commercial',
  },
  {
    id: 'proj-4',
    title: 'Fantasy Forest',
    prompt: 'Enchanted forest with glowing mushrooms and fireflies, a mystical deer walking through mist',
    model: AI_MODELS[1],
    status: 'completed',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=800&q=80',
    videoUrl: '#',
    duration: 10,
    createdAt: '2026-07-25T16:45:00Z',
    updatedAt: '2026-07-25T16:52:00Z',
    creditsUsed: 2.5,
    aspectRatio: '9:16',
    style: 'Fantasy',
  },
  {
    id: 'proj-5',
    title: 'Space Station',
    prompt: 'Interior of a futuristic space station, astronauts floating in zero gravity, Earth visible through the window',
    model: AI_MODELS[5],
    status: 'pending',
    duration: 12,
    createdAt: '2026-07-30T05:30:00Z',
    updatedAt: '2026-07-30T05:30:00Z',
    creditsUsed: 7.2,
    aspectRatio: '21:9',
    style: 'Sci-Fi',
  },
]

export const MOCK_TRANSACTIONS: CreditTransaction[] = [
  { id: 'tx-1', type: 'purchase', amount: 5000, description: 'Pro Plan Monthly', createdAt: '2026-07-01T00:00:00Z' },
  { id: 'tx-2', type: 'usage', amount: -6, description: 'Veo 3.1 — Neon Tokyo Drift', createdAt: '2026-07-28T14:35:00Z' },
  { id: 'tx-3', type: 'usage', amount: -2.5, description: 'Runway Gen-4.5 — Mountain Sunrise', createdAt: '2026-07-27T09:20:00Z' },
  { id: 'tx-4', type: 'usage', amount: -1.8, description: 'Luma Ray 3 — Product Showcase', createdAt: '2026-07-30T05:00:00Z' },
  { id: 'tx-5', type: 'bonus', amount: 500, description: 'Referral Bonus', createdAt: '2026-07-20T12:00:00Z' },
  { id: 'tx-6', type: 'usage', amount: -2.5, description: 'Kling 3.0 — Fantasy Forest', createdAt: '2026-07-25T16:52:00Z' },
]

export const MOCK_AB_TESTS: ABTest[] = [
  {
    id: 'ab-1',
    prompt: 'A serene Japanese garden with cherry blossoms falling, koi fish swimming in a pond',
    models: ['veo-3-1', 'kling-3-0', 'runway-gen-4-5'],
    results: [],
    status: 'completed',
    createdAt: '2026-07-26T10:00:00Z',
  },
]
